[package]
name = "raydium-cp-swap"
version = "0.2.0"
description = "Raydium constant product AMM, supports Token2022 and without Openbook"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "raydium_cp_swap"

[features]
no-entrypoint = []
no-log-ix-name = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
enable-log = []
devnet = []
client = []
anchor-debug = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "light-sdk/idl-build"]
test-sbf = []

[dependencies]
anchor-lang = { path = "../../../anchor/lang", features = ["init-if-needed", "idl-build"] }
anchor-spl = { path = "../../../anchor/spl", features = ["memo", "metadata", "idl-build"] }
spl-token-2022 = { version = "7.0.0", features = ["no-entrypoint"] }
spl-math = { version = "0.3", features = ["no-entrypoint"] }
uint = "0.10.0"
solana-security-txt = "1.1.1"
bytemuck = { version = "1.4.0", features = ["derive", "min_const_generics"] }
arrayref = { version = "0.3.6" }

light-sdk = { path = "../../../light-protocol-2/sdk-libs/sdk", features = ["anchor", "idl-build", "v2", "anchor-discriminator", "cpi-context"] }
light-sdk-types = { path = "../../../light-protocol-2/sdk-libs/sdk-types", features = ["anchor", "v2", "cpi-context"] }
light-hasher = { path = "../../../light-protocol-2/program-libs/hasher", features = ["solana"] }
light-macros = { path = "../../../light-protocol-2/program-libs/macros", features = ["solana"] }
light-sdk-macros = { path = "../../../light-protocol-2/sdk-libs/macros" }
light-compressed-account = { path = "../../../light-protocol-2/program-libs/compressed-account", features = ["solana", "std"] }
light-ctoken-sdk = { path = "../../../light-protocol-2/sdk-libs/ctoken-sdk", features = ["anchor", "compressible"] }
light-ctoken-types = { path = "../../../light-protocol-2/sdk-libs/ctoken-types" }
light-ctoken-interface = { path = "../../../light-protocol-2/program-libs/ctoken-interface", features = ["anchor"] }
light-compressible = { path = "../../../light-protocol-2/program-libs/compressible", features = ["anchor"] }
solana-pubkey = "2.2"
solana-program-error = "2.2"
solana-account-info = "2.2"
solana-cpi = "2.2"
solana-msg = "2.2"
solana-program = "2.2"
# Anchor 0.31 uses borsh 0.10 for compatibility
borsh = { version = "0.10.4", default-features = false }


[dev-dependencies]
quickcheck = "1.0.3"
proptest = "1.0"
rand = "0.9.0"

light-program-test = { path = "../../../light-protocol-2/sdk-libs/program-test", features = ["v2"] }
light-client = { path = "../../../light-protocol-2/sdk-libs/client", features = ["v2"] }
light-compressible-client = { path = "../../../light-protocol-2/sdk-libs/compressible-client", features = ["anchor"] }


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
