[package]
name = "raydium-cp-swap"
version = "0.2.0"
description = "Raydium constant product AMM, supports Token2022 and without Openbook"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "raydium_cp_swap"

[features]
no-entrypoint = []
no-log-ix-name = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
enable-log = []
devnet = []
client = []
anchor-debug = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
test-sbf = []

[dependencies]
anchor-lang = { version = "=0.31.1", features = ["init-if-needed", "idl-build"] }
anchor-spl = { version = "=0.31.1", git = "https://github.com/lightprotocol/anchor", rev = "d8a2b3d9", features = ["memo", "idl-build"] }
spl-token-2022 = { version = "7.0.0", features = ["no-entrypoint"] }
spl-math = { version = "0.3", features = ["no-entrypoint"] }
uint = "0.10.0"
solana-security-txt = "1.1.1"
bytemuck = { version = "1.4.0", features = ["derive", "min_const_generics"] }
arrayref = { version = "0.3.6" }

light-sdk = { path = "../../../light-protocol-2/sdk-libs/sdk", features = ["anchor", "anchor-discriminator", "v2", "idl-build", "cpi-context"] }
light-sdk-types = { path = "../../../light-protocol-2/sdk-libs/sdk-types", features = ["v2", "cpi-context"] }
light-hasher = { path = "../../../light-protocol-2/program-libs/hasher", features = ["solana"] }
light-macros = { path = "../../../light-protocol-2/program-libs/macros", features = ["solana"] }
light-sdk-macros = { path = "../../../light-protocol-2/sdk-libs/macros" }
light-compressible = { path = "../../../light-protocol-2/program-libs/compressible", features = ["anchor"] }
light-token-sdk = { path = "../../../light-protocol-2/sdk-libs/token-sdk", features = ["anchor", "compressible"] }
light-token-interface = { path = "../../../light-protocol-2/program-libs/token-interface", features = ["anchor"] }
light-token-types = { path = "../../../light-protocol-2/sdk-libs/token-types", features = ["anchor"] }
light-compressed-account = { path = "../../../light-protocol-2/program-libs/compressed-account", features = ["anchor"] }
solana-account-info = "2.2"
solana-program = "2.2"
solana-pubkey = "2.2"
solana-program-error = "2.2"


[dev-dependencies]
quickcheck = "1.0.3"
proptest = "1.0"
rand = "0.9.0"

light-program-test = { path = "../../../light-protocol-2/sdk-libs/program-test", features = ["v2"] }
light-client = { path = "../../../light-protocol-2/sdk-libs/client", features = ["v2"] }
light-compressible-client = { path = "../../../light-protocol-2/sdk-libs/compressible-client", features = ["anchor"] }


[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
